const baseApiUrl =  {
employee: 'https://core.vyaguta.lftechnology.com/api/core/users',
projects: 'https://projects.vyaguta.lftechnology.com/api/projects/',
timesheet: 'https://timesheet.vyaguta.lftechnology.com/api/timesheet/'
}

const token = {
    refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyOTMsImRhdGVvZkJpcnRoIjoiMTk5Ni0wNS0wN1QwMDowMDowMC4wMDBaIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9sbXMubGZ0ZWNobm9sb2d5LmNvbS9pbWFnZXMvNDA0LnBuZz9iZDU5Y2JiOS1hNDYxLTRhY2ItOGJjNS01MTE4ODVjODE4M2MiLCJlbXBJZCI6IjQwNCIsImVtcFN0YXR1cyI6IlBlcm1hbmVudCIsImZpcnN0TmFtZSI6IlNocmVlaml0IiwibGFzdE5hbWUiOiJSYWpiYW5zaGkiLCJlbWFpbCI6InNocmVlaml0cmFqYmFuc2hpQGxmdGVjaG5vbG9neS5jb20iLCJnZW5kZXIiOiJNQUxFIiwiZ2l0aHViSWQiOiJodHRwczovL2dpdGh1Yi5jb20vU0VSUEFOVCIsImlzSG9kIjpmYWxzZSwiaXNIciI6ZmFsc2UsImlzUmFmZmxlRWxpZ2libGUiOnRydWUsImlzU3VwZXJ2aXNvciI6ZmFsc2UsIm1pZGRsZU5hbWUiOm51bGwsIm1vYmlsZVBob25lIjoiOTgxODkxMTM3MCIsInRlbXBvcmFyeUFkZHJlc3MiOm51bGwsImJsb29kR3JvdXAiOiJBKyIsImlzUHJvamVjdE1hbmFnZXIiOmZhbHNlLCJpc1RlYW1MZWFkIjpmYWxzZSwiaXNBY2NvdW50TWFuYWdlciI6ZmFsc2UsImlzQ29hY2giOmZhbHNlLCJpc1Blb3BsZU9wcyI6ZmFsc2UsImlzUHJveHlwbSI6ZmFsc2UsImlzUmVzb3VyY2VNYW5hZ2VyIjpmYWxzZSwiY29hY2hJZCI6bnVsbCwic3VwZXJ2aXNvcklkIjo3NCwicGVybWFuZW50QWRkcmVzcyI6IkJhc3VuZGhhcmEsIEthdGhtYW5kdSIsInNreXBlSWQiOm51bGwsImhvbWVQaG9uZSI6bnVsbH0sImlhdCI6MTU3Mjc1OTY0MSwiZXhwIjoxNTcyNzYzMjQxfQ.fpxRSayt2lozJ1HD0OWUt0j6e2LmSGoyQrk56I-DBA4',
    accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoyOTMsImRhdGVvZkJpcnRoIjoiMTk5Ni0wNS0wN1QwMDowMDowMC4wMDBaIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9sbXMubGZ0ZWNobm9sb2d5LmNvbS9pbWFnZXMvNDA0LnBuZz9iZDU5Y2JiOS1hNDYxLTRhY2ItOGJjNS01MTE4ODVjODE4M2MiLCJlbXBJZCI6IjQwNCIsImVtcFN0YXR1cyI6IlBlcm1hbmVudCIsImZpcnN0TmFtZSI6IlNocmVlaml0IiwibGFzdE5hbWUiOiJSYWpiYW5zaGkiLCJlbWFpbCI6InNocmVlaml0cmFqYmFuc2hpQGxmdGVjaG5vbG9neS5jb20iLCJnZW5kZXIiOiJNQUxFIiwiZ2l0aHViSWQiOiJodHRwczovL2dpdGh1Yi5jb20vU0VSUEFOVCIsImlzSG9kIjpmYWxzZSwiaXNIciI6ZmFsc2UsImlzUmFmZmxlRWxpZ2libGUiOnRydWUsImlzU3VwZXJ2aXNvciI6ZmFsc2UsIm1pZGRsZU5hbWUiOm51bGwsIm1vYmlsZVBob25lIjoiOTgxODkxMTM3MCIsInRlbXBvcmFyeUFkZHJlc3MiOm51bGwsImJsb29kR3JvdXAiOiJBKyIsImlzUHJvamVjdE1hbmFnZXIiOmZhbHNlLCJpc1RlYW1MZWFkIjpmYWxzZSwiaXNBY2NvdW50TWFuYWdlciI6ZmFsc2UsImlzQ29hY2giOmZhbHNlLCJpc1Blb3BsZU9wcyI6ZmFsc2UsImlzUHJveHlwbSI6ZmFsc2UsImlzUmVzb3VyY2VNYW5hZ2VyIjpmYWxzZSwiY29hY2hJZCI6bnVsbCwic3VwZXJ2aXNvcklkIjo3NCwicGVybWFuZW50QWRkcmVzcyI6IkJhc3VuZGhhcmEsIEthdGhtYW5kdSIsInNreXBlSWQiOm51bGwsImhvbWVQaG9uZSI6bnVsbH0sImlhdCI6MTU3Mjc1OTY0MSwiZXhwIjoxNTcyNzYzMjQxfQ.fpxRSayt2lozJ1HD0OWUt0j6e2LmSGoyQrk56I-DBA4'
}


module.exports = {
baseApiUrl,
token
}